### ISSUE TITLE
Crashing after server address

### ISSUE THREAD

**Issue by JABirchall** [cydolo/TSC-Beta#2]
`TeamSpeak 3 - Server Crasher 3.7.0 Beta
Github: https://github.com/cydolo
discord: https://discordapp.com/invite/ZwgMfNz

Server Adress or Nickname:
185.211.247.26

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at TS3Client.Full.Ts3FullClient..ctor(EventDispatchType dispatcherType)
   at TeamSpeak_Server_Crasher.Program.Connect()
   at TeamSpeak_Server_Crasher.Program.Main(String[] args)
```

**Comment by cydolo** [comment]
You have installed NET Framework 4.7.2?
https://dotnet.microsoft.com/download/dotnet-framework/net472
It is recommended to use Windows 10

**Comment by JABirchall** [comment]
Thanks that fixed it.
